Next frontend
adamjonas/transcription-queue pull request #8
Opened 2023-03-07 11:48 UTC by Emmanuel-Develops

Closes #2 

The original frontend still exists on the repo. This frontend has to be configured for docker and where it is hosted.

@nassersaazi I noticed the original frontend had netlify redirects config, kindly host this frontend with vercel, nextJs integrates better with vercel.

Also, the authentication is a test auth by creating a Github OAuth app with my account. When the project's OAuth account is ready we can replace it.

2023-03-07 21:49 UTC, nassersaazi commented
i suggest you get rid of the original frontend directory altogether

2023-03-07 22:06 UTC, nassersaazi requested changes

2023-03-08 20:38 UTC, Emmanuel-Develops commented on frontend-next/yarn.lock
> +  integrity sha512-rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==
It helps maintain dependencies with yarn, we shouldn't ignore it

2023-03-08 20:38 UTC, Emmanuel-Develops commented on frontend-next/src/hooks/useTranscripts.ts
> +  // };
I'll remove that

2023-03-10 23:53 UTC, adamjonas commented
I'm on HEAD but getting an error

<img width="619" alt="Screen Shot 2023-03-10 at 6 48 05 PM" src="https://user-images.githubusercontent.com/755825/224449282-522b2d23-8542-4a20-928f-74987acb869d.png">


<img width="877" alt="Screen Shot 2023-03-10 at 6 47 12 PM" src="https://user-images.githubusercontent.com/755825/224449419-0182d0b2-1169-47aa-8de9-5b002b3b509a.png">

When I run on the daemon I get a CORS issue

<img width="955" alt="Screen Shot 2023-03-10 at 6 50 50 PM" src="https://user-images.githubusercontent.com/755825/224450165-67af795f-de48-40a8-b49f-94c1d24a903e.png">

2023-03-12 11:20 UTC, Emmanuel-Develops commented
I've fixed the error on HEAD

I can't recreate the CORS issue, ran it on `localhost:3001` and there was no issue

2023-03-12 12:33 UTC, merged